### ISSUE TITLE
https instead of http

### ISSUE THREAD

**Issue by walfc** [PrestaShop/gsitemap#35]
i cant see how to make the site work as https, the sitemap location and the called files are always http

**Comment by walfc** [comment]
Any update on this please?

**Comment by Geolim4** [comment]
It seem to be hardcoded atm :/

**Comment by chykalodmitry** [comment]
@walfc 
The module works good with ssl but after you changed your working shop from http to https you must delete the file in your root folder of Prestashop named 1_index_sitemap.xml and then recreate sitemap in module. After that open your sitemap in browser https://yourdomain.com/1_index_sitemap.xml and check if the nested sitemaps url has 'https'.
It happens because there is no function to delete the 1_index_sitemap.xml, only for nested sitemaps like 1_uk_0_sitemap.xml.

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53
